In [2]:
import numpy as np

In [3]:
benimDizim = np.arange(0,15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[3:8] = -5 #3 ve 8. index arasını -5 ile değiştirir

In [6]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [7]:
baskaDizi = np.arange(0,20)

In [8]:
slicingDizisi = baskaDizi[3:8]

In [9]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
slicingDizisi

array([3, 4, 5, 6, 7])

In [11]:
slicingDizisi[:] = 700 #dizimizdeki tüm elemanları 700 ile değiştirir

In [12]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [13]:
baskaDizi 
#slicing dizimiz baska dizi içerindeki bir parçanın alındığı farklı bir dizi iken oradaki değişiklikler orjinal dizimizede yansır

array([  0,   1,   2, 700, 700, 700, 700, 700,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [14]:
ornekDizi = np.arange(0,20)

In [15]:
ornekDiziKopyasi = ornekDizi.copy() #dizimizin kopyasını oluşturduk

In [16]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
ornekDiziSlicing = ornekDiziKopyasi[3:8]

In [19]:
ornekDiziSlicing

array([3, 4, 5, 6, 7])

In [20]:
ornekDiziSlicing[:] = 700

In [21]:
ornekDiziSlicing

array([700, 700, 700, 700, 700])

In [22]:
ornekDiziKopyasi #Slicing dizimiz bu dizi içerisinden oluştuğu için değişkiler yansıdı

array([  0,   1,   2, 700, 700, 700, 700, 700,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [23]:
ornekDizi # orjinal dizide değişim olmadı çünkü biz bu dizinin kopyasını oluşturduk ve orjinal dizimiz değişmeden kaldı

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Matrix İndex'leri

In [24]:
benimListem = [[10,20,30],[20,30,40],[30,40,50]]

In [25]:
benimMatrixListem = np.array(benimListem)

In [26]:
benimMatrixListem

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [27]:
benimMatrixListem[1,2] #index'i 1 olan satırdan index'i 2 olan elemanı getirir

40

In [28]:
benimMatrixListem[1:,2:] #1 index numaralı satırdan itibaren son satıra kadar 2 numaralı index ve sonrasında bulunan kolondaki elemanları alır

array([[40],
       [50]])

In [29]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [30]:
yeniMatrix = np.array(yeniListe)

In [31]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
yeniMatrix[[0,2,4]] # seçili index numaralarındaki dizileri getirir

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## Operasyonlar

In [33]:
yeniDizi = np.random.randint(1,100,20)

In [34]:
yeniDizi

array([80, 57, 78, 31, 27, 50, 40, 28, 59, 97,  2, 63, 33, 31, 15, 85, 93,
       69, 90, 77])

In [35]:
sonucDizisi = yeniDizi > 24

In [36]:
sonucDizisi # 24'den büyük olan sayıları True olarak gösterir

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [37]:
yeniDizi[sonucDizisi] # sadece True olan değerleri yani 24'den büyük olan değerleri döndürür

array([80, 57, 78, 31, 27, 50, 40, 28, 59, 97, 63, 33, 31, 85, 93, 69, 90,
       77])

In [38]:
yeniDizi[yeniDizi > 24] #2. yöntem

array([80, 57, 78, 31, 27, 50, 40, 28, 59, 97, 63, 33, 31, 85, 93, 69, 90,
       77])

In [41]:
sonDizi = np.arange(0,24)

In [42]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
sonDizi + sonDizi #dizilerle 4 işlem yapılabilir

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [48]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [50]:
np.sqrt(sonDizi) #liste elemanlarının karekökünü alır

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])