In [1]:
import numpy as np

## Numpy array

In [2]:
myList = [10,20,30]

In [3]:
np.array(myList) #listemizi numpy dizisine döndürdük

array([10, 20, 30])

In [5]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [7]:
np.array(matrixListesi) #numpy array'leri liste içinde listeleri matrix biçiminde gösterir

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [8]:
list(range(0,10)) #liste ile range kullanımı

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(0,10) # numpy ile range kullanımı. array oluşturur

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,20,2) # 2'şer atlayarak yazar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros and ones

In [16]:
np.zeros(5) # 5 elemanlı içinde 0 bulunan dizi oluşturur

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,2)) #matrix şeklinde 0 elemanları bulunan dizi oluşturur

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.ones(5) # zeros ile aynı şekilde işler ama listede 1 bulunur

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## linspace

In [20]:
np.linspace(0,20,8) #0 ile 20 arasını 8 eş parçaya böler

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

## eye

In [21]:
np.eye(5) # 5 tane matrix dizisi oluşturur 1 ve 0 bulunur ve 1 her listede 1 index atlar

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [22]:
np.random.randn(4) #rastgele 4 elemanlı bir dizi oluşturur

array([ 0.09085152,  0.49282714, -0.66557749, -0.13255665])

In [23]:
np.random.rand(4,4) #rastgele 4 elemanlı 4 dizi oluşturur

array([[0.55331112, 0.13244899, 0.62240282, 0.43643654],
       [0.98698637, 0.91436423, 0.91482252, 0.78557646],
       [0.47518603, 0.71426554, 0.88634084, 0.1691599 ],
       [0.76611658, 0.32994126, 0.66182108, 0.26154923]])

In [27]:
np.random.randint(0,10) # 0 ve 10 arasında(10 dahil değil) 1 tane rastgele sayı yazar

0

In [28]:
np.random.randint(0,100,5) # 5 tane rastgele değer döndürür

array([47, 33, 11, 19, 44])

## numpy array methods

In [34]:
myNumpyArray = np.arange(0,30)
myRandomArray = np.random.randint(0,100,20)

In [35]:
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
myRandomArray

array([61, 28, 26,  8, 74, 96, 16, 42, 70, 14, 26, 59, 74, 14, 90, 38, 61,
       50, 31, 41])

In [37]:
myNumpyArray.reshape(5,6) # listeyi matrix biçiminde bölerek yazar

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
myRandomArray.max() #listdeki en büyük sayıyı verir

96

In [39]:
myRandomArray.min() #dizideki en küçük sayıyı verir

8

In [40]:
myRandomArray.argmax() # en  büyük sayının index'ini verir

5

In [41]:
myRandomArray.argmin() # en küçük sayının index'ini verir

3

In [42]:
reshapeArray = myNumpyArray.reshape(5,6)

In [43]:
reshapeArray.shape #listenin güncel biçimini verir

(5, 6)